AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template to create an admin role that trusts a specific account.

Parameters:
  TrustedAccountId:
    Type: String
    Description: The AWS account ID that this role will trust.

Resources:
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "CloudCanvasGenericCrossAccountAdminRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${TrustedAccountId}:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      Description: "An admin role that trusts a specific account."

Outputs:
  AdminRoleArn:
    Description: "The ARN of the created admin role."
    Value: !GetAtt AdminRole.Arn
